# Frame offsets in meters
camera_x_offset: 0.24 # X offset from robot center to camera frame
camera_Z_offset: 0.13 # Z offset from robot center to camera frame
launcher_z_offset: 0.265 # Z offset from robot center to launcher frame 

# New Coordinate Frames
camera_frame_id: camera_link
world_frame_id: world
robot_base_frame_id: robot_base
robot_center_frame_id: robot_center
launcher_frame_id: launcher
