rate: 20.0 # rate to run the detector (hz)

# Coordinate frame definitions
frame/camera_frame_id: camera_link
frame/world_frame_id: world
frame/robot_base_frame_id: robot_base
frame/robot_center_frame_id: robot_center
frame/launcher_frame_id: launcher

# Geometric fixed frame offsets
geometry/camera_x_offset: 0.133 # X offset from robot center to camera frame
geometry/camera_z_offset: 0.127 # Z offset from robot center to camera frame
geometry/launcher_z_offset: 0.2765 # Z offset from robot center to launcher frame 
